version: '3.5'
services:

  p_proxy:
    build:
      context: "./env/prod/proxy"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - p_spa
      - p_api
    volumes:
      - ./env/prod/proxy/certbot/data:/etc/letsencrypt
      - ./env/prod/proxy/certbot/www:/var/www/certbot
    environment:
      - SERVER_NAME=${NGINX_SERVER_NAME:sospandemia.org}
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  p_certbot:
    image: certbot/certbot
    volumes:
      - ./env/prod/proxy/certbot/data:/etc/letsencrypt
      - ./env/prod/proxy/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  p_spa:
    build:
      context: "./env/prod/spa"

  p_web:
    build:
      context: "./env/prod/api"
      dockerfile: web.Dockerfile
    working_dir: /var/www

  p_api:
    build:
      context: "./env/prod/api"
      dockerfile: api.Dockerfile
    working_dir: /var/www
    volumes:
      - p_storage-volume:/var/www/storage

  p_db:
    image: mdillon/postgis:11
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - p_database-volume:/var/lib/postgresql/data

  p_redis:
    image: redis:5

volumes:
  p_database-volume:
  p_storage-volume:
