version: '3.5'
services:

  proxy:
    build:
      context: "./env/prod/proxy"
    ports:
      - "80:80"

  spa:
    build:
      context: "./env/prod/spa"

  web:
    build:
      context: "./env/prod/api"
      dockerfile: web.Dockerfile
    working_dir: /var/www

  api:
    build:
      context: "./env/prod/api"
      dockerfile: api.Dockerfile
    working_dir: /var/www

  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - database-volume:/var/lib/postgresql/data

  redis:
    image: redis:5

volumes:
  database-volume:
